###########################################################
# Docker container build action.
###########################################################

name: Docker Build Smarte Edge monitor module

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Package Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: docker build module
      run: |
        docker buildx build --push \
            --tag ghcr.io/northropbv/edge-runtime-test-module-AMD64:01 \
            --platform linux/amd64 .
